/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package server

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/transfer"

	svcapitypes "github.com/crossplane/provider-aws/apis/transfer/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribeServerInput returns input for read
// operation.
func GenerateDescribeServerInput(cr *svcapitypes.Server) *svcsdk.DescribeServerInput {
	res := &svcsdk.DescribeServerInput{}

	if cr.Status.AtProvider.ServerID != nil {
		res.SetServerId(*cr.Status.AtProvider.ServerID)
	}

	return res
}

// GenerateServer returns the current state in the form of *svcapitypes.Server.
func GenerateServer(resp *svcsdk.DescribeServerOutput) *svcapitypes.Server {
	cr := &svcapitypes.Server{}

	if resp.Server.ServerId != nil {
		cr.Status.AtProvider.ServerID = resp.Server.ServerId
	} else {
		cr.Status.AtProvider.ServerID = nil
	}

	return cr
}

// GenerateCreateServerInput returns a create input.
func GenerateCreateServerInput(cr *svcapitypes.Server) *svcsdk.CreateServerInput {
	res := &svcsdk.CreateServerInput{}

	if cr.Spec.ForProvider.Certificate != nil {
		res.SetCertificate(*cr.Spec.ForProvider.Certificate)
	}
	if cr.Spec.ForProvider.Domain != nil {
		res.SetDomain(*cr.Spec.ForProvider.Domain)
	}
	if cr.Spec.ForProvider.EndpointDetails != nil {
		f2 := &svcsdk.EndpointDetails{}
		if cr.Spec.ForProvider.EndpointDetails.AddressAllocationIDs != nil {
			f2f0 := []*string{}
			for _, f2f0iter := range cr.Spec.ForProvider.EndpointDetails.AddressAllocationIDs {
				var f2f0elem string
				f2f0elem = *f2f0iter
				f2f0 = append(f2f0, &f2f0elem)
			}
			f2.SetAddressAllocationIds(f2f0)
		}
		if cr.Spec.ForProvider.EndpointDetails.SecurityGroupIDs != nil {
			f2f1 := []*string{}
			for _, f2f1iter := range cr.Spec.ForProvider.EndpointDetails.SecurityGroupIDs {
				var f2f1elem string
				f2f1elem = *f2f1iter
				f2f1 = append(f2f1, &f2f1elem)
			}
			f2.SetSecurityGroupIds(f2f1)
		}
		if cr.Spec.ForProvider.EndpointDetails.SubnetIDs != nil {
			f2f2 := []*string{}
			for _, f2f2iter := range cr.Spec.ForProvider.EndpointDetails.SubnetIDs {
				var f2f2elem string
				f2f2elem = *f2f2iter
				f2f2 = append(f2f2, &f2f2elem)
			}
			f2.SetSubnetIds(f2f2)
		}
		if cr.Spec.ForProvider.EndpointDetails.VPCEndpointID != nil {
			f2.SetVpcEndpointId(*cr.Spec.ForProvider.EndpointDetails.VPCEndpointID)
		}
		if cr.Spec.ForProvider.EndpointDetails.VPCID != nil {
			f2.SetVpcId(*cr.Spec.ForProvider.EndpointDetails.VPCID)
		}
		res.SetEndpointDetails(f2)
	}
	if cr.Spec.ForProvider.EndpointType != nil {
		res.SetEndpointType(*cr.Spec.ForProvider.EndpointType)
	}
	if cr.Spec.ForProvider.HostKey != nil {
		res.SetHostKey(*cr.Spec.ForProvider.HostKey)
	}
	if cr.Spec.ForProvider.IDentityProviderDetails != nil {
		f5 := &svcsdk.IdentityProviderDetails{}
		if cr.Spec.ForProvider.IDentityProviderDetails.InvocationRole != nil {
			f5.SetInvocationRole(*cr.Spec.ForProvider.IDentityProviderDetails.InvocationRole)
		}
		if cr.Spec.ForProvider.IDentityProviderDetails.URL != nil {
			f5.SetUrl(*cr.Spec.ForProvider.IDentityProviderDetails.URL)
		}
		res.SetIdentityProviderDetails(f5)
	}
	if cr.Spec.ForProvider.IDentityProviderType != nil {
		res.SetIdentityProviderType(*cr.Spec.ForProvider.IDentityProviderType)
	}
	if cr.Spec.ForProvider.LoggingRole != nil {
		res.SetLoggingRole(*cr.Spec.ForProvider.LoggingRole)
	}
	if cr.Spec.ForProvider.Protocols != nil {
		f8 := []*string{}
		for _, f8iter := range cr.Spec.ForProvider.Protocols {
			var f8elem string
			f8elem = *f8iter
			f8 = append(f8, &f8elem)
		}
		res.SetProtocols(f8)
	}
	if cr.Spec.ForProvider.SecurityPolicyName != nil {
		res.SetSecurityPolicyName(*cr.Spec.ForProvider.SecurityPolicyName)
	}
	if cr.Spec.ForProvider.Tags != nil {
		f10 := []*svcsdk.Tag{}
		for _, f10iter := range cr.Spec.ForProvider.Tags {
			f10elem := &svcsdk.Tag{}
			if f10iter.Key != nil {
				f10elem.SetKey(*f10iter.Key)
			}
			if f10iter.Value != nil {
				f10elem.SetValue(*f10iter.Value)
			}
			f10 = append(f10, f10elem)
		}
		res.SetTags(f10)
	}

	return res
}

// GenerateUpdateServerInput returns an update input.
func GenerateUpdateServerInput(cr *svcapitypes.Server) *svcsdk.UpdateServerInput {
	res := &svcsdk.UpdateServerInput{}

	if cr.Spec.ForProvider.Certificate != nil {
		res.SetCertificate(*cr.Spec.ForProvider.Certificate)
	}
	if cr.Spec.ForProvider.EndpointDetails != nil {
		f1 := &svcsdk.EndpointDetails{}
		if cr.Spec.ForProvider.EndpointDetails.AddressAllocationIDs != nil {
			f1f0 := []*string{}
			for _, f1f0iter := range cr.Spec.ForProvider.EndpointDetails.AddressAllocationIDs {
				var f1f0elem string
				f1f0elem = *f1f0iter
				f1f0 = append(f1f0, &f1f0elem)
			}
			f1.SetAddressAllocationIds(f1f0)
		}
		if cr.Spec.ForProvider.EndpointDetails.SecurityGroupIDs != nil {
			f1f1 := []*string{}
			for _, f1f1iter := range cr.Spec.ForProvider.EndpointDetails.SecurityGroupIDs {
				var f1f1elem string
				f1f1elem = *f1f1iter
				f1f1 = append(f1f1, &f1f1elem)
			}
			f1.SetSecurityGroupIds(f1f1)
		}
		if cr.Spec.ForProvider.EndpointDetails.SubnetIDs != nil {
			f1f2 := []*string{}
			for _, f1f2iter := range cr.Spec.ForProvider.EndpointDetails.SubnetIDs {
				var f1f2elem string
				f1f2elem = *f1f2iter
				f1f2 = append(f1f2, &f1f2elem)
			}
			f1.SetSubnetIds(f1f2)
		}
		if cr.Spec.ForProvider.EndpointDetails.VPCEndpointID != nil {
			f1.SetVpcEndpointId(*cr.Spec.ForProvider.EndpointDetails.VPCEndpointID)
		}
		if cr.Spec.ForProvider.EndpointDetails.VPCID != nil {
			f1.SetVpcId(*cr.Spec.ForProvider.EndpointDetails.VPCID)
		}
		res.SetEndpointDetails(f1)
	}
	if cr.Spec.ForProvider.EndpointType != nil {
		res.SetEndpointType(*cr.Spec.ForProvider.EndpointType)
	}
	if cr.Spec.ForProvider.HostKey != nil {
		res.SetHostKey(*cr.Spec.ForProvider.HostKey)
	}
	if cr.Spec.ForProvider.IDentityProviderDetails != nil {
		f4 := &svcsdk.IdentityProviderDetails{}
		if cr.Spec.ForProvider.IDentityProviderDetails.InvocationRole != nil {
			f4.SetInvocationRole(*cr.Spec.ForProvider.IDentityProviderDetails.InvocationRole)
		}
		if cr.Spec.ForProvider.IDentityProviderDetails.URL != nil {
			f4.SetUrl(*cr.Spec.ForProvider.IDentityProviderDetails.URL)
		}
		res.SetIdentityProviderDetails(f4)
	}
	if cr.Spec.ForProvider.LoggingRole != nil {
		res.SetLoggingRole(*cr.Spec.ForProvider.LoggingRole)
	}
	if cr.Spec.ForProvider.Protocols != nil {
		f6 := []*string{}
		for _, f6iter := range cr.Spec.ForProvider.Protocols {
			var f6elem string
			f6elem = *f6iter
			f6 = append(f6, &f6elem)
		}
		res.SetProtocols(f6)
	}
	if cr.Spec.ForProvider.SecurityPolicyName != nil {
		res.SetSecurityPolicyName(*cr.Spec.ForProvider.SecurityPolicyName)
	}
	if cr.Status.AtProvider.ServerID != nil {
		res.SetServerId(*cr.Status.AtProvider.ServerID)
	}

	return res
}

// GenerateDeleteServerInput returns a deletion input.
func GenerateDeleteServerInput(cr *svcapitypes.Server) *svcsdk.DeleteServerInput {
	res := &svcsdk.DeleteServerInput{}

	if cr.Status.AtProvider.ServerID != nil {
		res.SetServerId(*cr.Status.AtProvider.ServerID)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
